#ifndef _FragmentFragment_h_
#define _FragmentFragment_h_


// Header generated from binary by WriteAsBinHeader()..
static const int FragmentFragmentLength = 88;
static const unsigned int FragmentFragment[FragmentFragmentLength]={
	0x20205350,	0xFFFF0008,	0x00000048,	0x01020000,	0x00000009,	0x00000003,	0x00000000,	0x00000000,	0x00000001,	0x00000000,
	0x00000001,	0x00000001,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x0000001A,	0x00000000,	0x18000000,	0x0718FF07,
	0x230820FF,	0x00000000,	0x08FF0708,	0x0718FF07,	0x0EF82105,	0x00000000,	0x02000000,	0x01014402,	0x037821E4,	0x00000000,
	0x00000000,	0x81010000,	0x114021E4,	0x00000000,	0x00000000,	0x01010001,	0x034021FF,	0x00000000,	0x00000000,	0x01010000,
	0x074021FF,	0x00000000,	0x00000000,	0x00000000,	0x00B821A4,	0x00000000,	0x00000000,	0x0101E407,	0x107A10E4,	0x00000000,
	0x00000000,	0x00000000,	0x1E000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x3F800000,	0x3F800000,
	0x3F800000,	0x3F800000,	0x00000000,	0x00000000,	0x00000000,	0x00000000,	0x00000013,	0x00000006,	0x00000003,	0x00000000,
	0x00000000,	0x00000000,	0x00000007,	0x00000003,	0x00020001,	0x00000008,	0x00000008,	0x0000000A,	0x0000000F,	0x00030005,
	0x00000000,	0x44786554,	0x00306D69,	0x49786554,	0x6567616D,	0x76003073,	0x7865745F,	0x00000043,};

//checksum generated by simpleCheckSum()
static const unsigned int FragmentFragmentCheckSum = 71;

static const char* FragmentFragmentText = 
	"precision highp float;\n"
	"\n"
	"uniform sampler2D TexImages0;\n"
	"\n"
	"varying vec2 v_texC;\n"
	"\n"
	"void main()\n"
	"{\n"
	"    gl_FragColor = texture2D(TexImages0, v_texC);\n"
	"}\n"
	"";

#ifdef GL_HELPERS_INCLUDED
//glHelpers.h must be included BEFORE any of the shader header files. Also make sure you have the latest version of glHelpers.h
static ghShader FragmentFragmentShader(FragmentFragmentText, FragmentFragment, FragmentFragmentLength, FragmentFragmentCheckSum);


#endif


#endif //_FragmentFragment_h_
